name: Get New Posts
on:
  schedule: # Run workflow automatically
    - cron: '0 1 1 * *' # Runs every day one o clock
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-hashnde-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://georgebawesome.hashnode.dev/rss.xml,https://overreacted.io/rss.xml,https://blog.saviomartin.com/rss.xml"
          max_post_count: "10"
