name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for contacting us. Will let you know more about this issue soon.'
        pr-message: 'Thankyou for your support. We will check your PR and if there are no issues, it will be merged.'
